import 'package:flutter/material.dart';
import 'package:saathi_user/components/report_screen/conversation_report.dart';
import 'package:saathi_user/components/report_screen/interests.dart';
import 'package:saathi_user/components/report_screen/stress_meter.dart';
import 'package:saathi_user/components/report_screen/top_bar.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';


class ReportScreen extends StatefulWidget {
  const ReportScreen({super.key});

  @override
  State<ReportScreen> createState() => _ReportScreenState();
}

class _ReportScreenState extends State<ReportScreen> {
  Map<String, dynamic> reportData = {
    "last_updated": "12:34, 18/02/2025",
    "emotion": "neutral",
    "conversations": 13,
    "stress": "Stress Free",
    "stressSummary": "Your child is very happy today !!",
    "interests_summary": "Reading, Badminton, Football, Swimming",
    "total_duration": "4hr 39min",

    "conversation_list": [
      {
        "date": "23 March 2025",
        "time": "12:05 PM", "duration": "42 min",
        "summary": "This small summary will be generated by the Gemini model after every conversation with Aasha",
        "emotion": "Happy and Anxious",
        "stress": "Stressed!",
        "stressSummary": "This stress summary will be generated by the Gemini model after every conversation with Aasha!",
        "interests": "This interest summary will be generated by the Gemini model after every conversation with Aasha!"
      },
      {
        "date": "21 March 2025",
        "time": "12:05 PM", "duration": "42 min",
        "summary": "This small summary will be generated by the Gemini model after every conversation with Aasha",
        "emotion": "Happy and Anxious",
        "stress": "Stressed!",
        "stressSummary": "This stress summary will be generated by the Gemini model after every conversation with Aasha!",
        "interests": "This interest summary will be generated by the Gemini model after every conversation with Aasha!"
      },
      {
        "date": "18 March 2025",
        "time": "12:05 PM", "duration": "42 min",
        "summary": "This small summary will be generated by the Gemini model after every conversation with Aasha",
        "emotion": "Happy and Anxious",
        "stress": "Stressed!",
        "stressSummary": "This stress summary will be generated by the Gemini model after every conversation with Aasha!",
        "interests": "This interest summary will be generated by the Gemini model after every conversation with Aasha!"
      },
    ]
  };
  // Map<String, dynamic> reportData = {};

  @override
  void initState() {
    super.initState();
    fetchReport();
  }

  Future<void> fetchReport() async {
    final prefs = await SharedPreferences.getInstance();
    String? sessionCookie = prefs.getString('session_cookie');
    if (sessionCookie == null) {
      return;
    }

    try {
      print("Printing sessionCookie: $sessionCookie");
      final reportResponse = await http.get(
        Uri.parse("${dotenv.env['BASE_URL']}/child/fetch_summary"),
        headers: {'Content-Type': 'application/json', 'Cookie': sessionCookie},
      );
      
      if (reportResponse.statusCode == 200) {
        setState(() {
          reportData = jsonDecode(reportResponse.body);
          print('${reportData['stress']} ${reportData['stress'].length}');
        });
      } else {
        print('Failed to load report');
      }
    } catch (e) {
      print("Error: $e");
    }
  }

  final Map<String, List<Color>> moodColorMap = {
    "Happy": [Color(0xFF5CFD87), Color(0xFF177630)],
    "Sad": [Color(0xFF4682B4), Color(0xFFC7DCFF)],
    "Fearful": [Color(0xFF483D8B), Color(0xFFE9EDFF)],
    "Angry": [Color(0xFFF5C1C1), Color(0xFFEB4335)], 
    "Calm": [Color(0xFF87CEEB), Color(0xFF421FDA)],
    "Disgust": [Color(0xFF6B8E23), Color(0xFFE9FFEA)],
    "Surprised": [Color(0xFFFFA500), Color(0xFFFFF5E9)],
    "Neutral": [Color(0xFFFFE573), Color(0xFFE78906)]
  };

  @override
  Widget build(BuildContext contex) {
    return Scaffold(
      body: SafeArea(
        child: Column(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          TopBar(),
          Container(
            margin: EdgeInsets.all(8),
            alignment: Alignment.topLeft,
            child: Text(
              'lastUpdated: ${reportData['last_updated']}',
              style: TextStyle(
                fontFamily: "Inter",
                fontSize: 12,
                color: Colors.black
              )
            )
          ),
          Container(
            margin: EdgeInsets.only(left: 8, right: 8, bottom: 8),
            padding: EdgeInsets.all(8),
            height: MediaQuery.of(context).size.height * 0.25,
            width: MediaQuery.of(context).size.width * 0.95,
            decoration: BoxDecoration(
              border: Border.all(color: Colors.black),
              borderRadius: BorderRadius.circular(10),
              color: Colors.white
            ),
            child: Align(
              alignment: Alignment.center,
              child: Text(
                "emotion graph",
                style: TextStyle(
                  fontFamily: "Inter",
                  fontSize: 18,
                  color: Colors.black,
                  fontWeight: FontWeight.bold
                )
              )
            )
          ),
          Row(
            children: [
              Container(
                margin: EdgeInsets.all(8),
                padding: EdgeInsets.all(8),
                height: MediaQuery.of(context).size.height * 0.15,
                width: MediaQuery.of(context).size.width * 0.55,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(10),
                  color: moodColorMap[reportData["emotion"]]?[0]
                ),
                child: Column(
                  children: [
                    Align(
                      alignment: Alignment.topLeft,
                      child: Text(
                        "Overall Mood",
                        style: TextStyle(
                          color: moodColorMap[reportData["emotion"]]?[1],
                          fontSize: 16,
                          fontWeight: FontWeight.bold
                        )
                      )
                    ),
                    Expanded(
                      // alignment: Alignment.center,
                      child: Align(
                        alignment: Alignment.center,
                        child: Text(
                          '${reportData["emotion"]}',
                          style: TextStyle(
                            color: moodColorMap[reportData["emotion"]]?[1],
                            fontWeight: FontWeight.bold,
                            fontSize: 24
                          )
                        )
                      )
                    )
                  ]
                )
              ),
              Expanded(
                child: Container(
                  margin: EdgeInsets.only(bottom: 8, top: 8, right: 8),
                  padding: EdgeInsets.all(8),
                  height: MediaQuery.of(context).size.height * 0.15,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(10),
                    color: Color(0xFFFAD4C6)
                  ),
                  child: Column(
                    children: [
                      Align(
                        alignment: Alignment.centerLeft,
                        child: Text(
                          "Conversations",
                          style: TextStyle(
                            color: Color(0xFF363636),
                            fontSize: 18, 
                            fontWeight: FontWeight.bold
                          )
                        )
                      ),
                      Align(
                        alignment: Alignment.topLeft,
                        child: Text(
                          "(past 7 days)",
                          style: TextStyle(
                            color: Color(0xFF363636),
                            fontSize: 12,
                            fontWeight: FontWeight.bold
                          )
                        )
                      ),
                      Expanded(
                        // alignment: Alignment.center,
                        child: Align(
                          alignment: Alignment.center,
                          child: Text(
                            reportData["conversations"].toString(),
                            style: TextStyle(
                              color: Color(0xFF363636),
                              fontWeight: FontWeight.bold,
                              fontSize: 24
                            )
                          )
                        )
                      )
                    ]
                  )
                )
              )
            ]
          ), 
          Row(
            children: [
              StressMeterWidget(reportData: reportData),
              Expanded(
                child: Column(
                  children: [
                    Container(
                      margin: EdgeInsets.only(bottom: 8, top: 8, left: 4, right: 8),
                      padding: EdgeInsets.all(8),
                      height: MediaQuery.of(context).size.height * 0.15,
                      decoration: BoxDecoration(
                        color: Color(0xFFFFAA8A),
                        borderRadius: BorderRadius.circular(10)
                      ),
                      child: Column(
                        children: [
                          Align(
                            alignment: Alignment.centerLeft,
                            child: Text(
                              "Time spent (avg.)",
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold
                              )
                            )
                          ),
                          Expanded(
                            child: Align(
                              alignment: Alignment.center,
                              child: Text(
                                reportData["total_duration"].toString(),
                                style: TextStyle(
                                  color: Color(0xFF363636),
                                  fontWeight: FontWeight.bold,
                                  fontSize: 24
                                )
                              )
                            )
                          )
                        ]
                      )
                    ),
                    Interests(reportData: reportData)
                  ]
                )
              )
            ]
          ),
          ConversationReport(reportData: reportData)
        ]
      )
    )
    );
  }
}