import 'package:flutter/material.dart';
import 'package:saathi_user/components/report_screen/conversation_report.dart';
import 'package:saathi_user/components/report_screen/interests.dart';
import 'package:saathi_user/components/report_screen/stress_meter.dart';
import 'package:saathi_user/components/report_screen/top_bar.dart';

class ReportScreen extends StatefulWidget {
  const ReportScreen({super.key});

  @override
  State<ReportScreen> createState() => _ReportScreenState();
}

class _ReportScreenState extends State<ReportScreen> {
  Map<String, Object> reportData = {
    "lastUpdated": "12:34, 18/02/2025",
    "mood": "Neutral",
    "conversations": 13,
    "stress": "Stress Free",
    "stressReason": "Your child is very happy today !!",
    "interests": "Reading, Badminton, Football, Swimming",
    "timeSpent": "4hr 39min",

    "conversationList": [
      {
        "date": "23 March 2025",
        "time": "12:05 PM", "duration": "42 min",
        "summary": "This small summary will be generated by the Gemini model after every conversation with Aasha",
        "emotion": "Happy and Anxious",
        "stress": "Stressed!",
        "stressSummary": "This stress summary will be generated by the Gemini model after every conversation with Aasha!",
        "interests": "This interest summary will be generated by the Gemini model after every conversation with Aasha!"
      },
      {
        "date": "21 March 2025",
        "time": "12:05 PM", "duration": "42 min",
        "summary": "This small summary will be generated by the Gemini model after every conversation with Aasha",
        "emotion": "Happy and Anxious",
        "stress": "Stressed!",
        "stressSummary": "This stress summary will be generated by the Gemini model after every conversation with Aasha!",
        "interests": "This interest summary will be generated by the Gemini model after every conversation with Aasha!"
      },
      {
        "date": "18 March 2025",
        "time": "12:05 PM", "duration": "42 min",
        "summary": "This small summary will be generated by the Gemini model after every conversation with Aasha",
        "emotion": "Happy and Anxious",
        "stress": "Stressed!",
        "stressSummary": "This stress summary will be generated by the Gemini model after every conversation with Aasha!",
        "interests": "This interest summary will be generated by the Gemini model after every conversation with Aasha!"
      },
    ]
  };

  final Map<String, List<Color>> moodColorMap = {
    "Happy": [Color(0xFF5CFD87), Color(0xFF177630)],
    "Sad": [Color(0xFF9CD8FD), Color(0xFF0060FF)],
    "Anxious": [Color(0xFFB0B0B0), Color(0xFF000000)],
    "Angry": [Color(0xFFF5C1C1), Color(0xFFEB4335)], 
    "Neutral": [Color(0xFFFFE573), Color(0xFFE78906)]
  };

  @override
  Widget build(BuildContext contex) {
    return Scaffold(
      body: SafeArea(
        child: Column(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          TopBar(),
          Container(
            margin: EdgeInsets.all(8),
            alignment: Alignment.topLeft,
            child: Text(
              'lastUpdated: ${reportData['lastUpdated']}',
              style: TextStyle(
                fontFamily: "Inter",
                fontSize: 12,
                color: Colors.black
              )
            )
          ),
          Container(
            margin: EdgeInsets.only(left: 8, right: 8, bottom: 8),
            padding: EdgeInsets.all(8),
            height: MediaQuery.of(context).size.height * 0.25,
            width: MediaQuery.of(context).size.width * 0.95,
            decoration: BoxDecoration(
              border: Border.all(color: Colors.black),
              borderRadius: BorderRadius.circular(10),
              color: Colors.white
            ),
            child: Align(
              alignment: Alignment.center,
              child: Text(
                "emotion graph",
                style: TextStyle(
                  fontFamily: "Inter",
                  fontSize: 18,
                  color: Colors.black,
                  fontWeight: FontWeight.bold
                )
              )
            )
          ),
          Row(
            children: [
              Container(
                margin: EdgeInsets.all(8),
                padding: EdgeInsets.all(8),
                height: MediaQuery.of(context).size.height * 0.15,
                width: MediaQuery.of(context).size.width * 0.55,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(10),
                  color: moodColorMap[reportData["mood"]]?[0]
                ),
                child: Column(
                  children: [
                    Align(
                      alignment: Alignment.topLeft,
                      child: Text(
                        "Overall Mood",
                        style: TextStyle(
                          color: moodColorMap[reportData["mood"]]?[1],
                          fontSize: 16,
                          fontWeight: FontWeight.bold
                        )
                      )
                    ),
                    Expanded(
                      // alignment: Alignment.center,
                      child: Align(
                        alignment: Alignment.center,
                        child: Text(
                          '${reportData["mood"]}',
                          style: TextStyle(
                            color: moodColorMap[reportData["mood"]]?[1],
                            fontWeight: FontWeight.bold,
                            fontSize: 24
                          )
                        )
                      )
                    )
                  ]
                )
              ),
              Expanded(
                child: Container(
                  margin: EdgeInsets.only(bottom: 8, top: 8, right: 8),
                  padding: EdgeInsets.all(8),
                  height: MediaQuery.of(context).size.height * 0.15,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(10),
                    color: Color(0xFFFAD4C6)
                  ),
                  child: Column(
                    children: [
                      Align(
                        alignment: Alignment.centerLeft,
                        child: Text(
                          "Conversations",
                          style: TextStyle(
                            color: Color(0xFF363636),
                            fontSize: 18, 
                            fontWeight: FontWeight.bold
                          )
                        )
                      ),
                      Align(
                        alignment: Alignment.topLeft,
                        child: Text(
                          "(past 7 days)",
                          style: TextStyle(
                            color: Color(0xFF363636),
                            fontSize: 12,
                            fontWeight: FontWeight.bold
                          )
                        )
                      ),
                      Expanded(
                        // alignment: Alignment.center,
                        child: Align(
                          alignment: Alignment.center,
                          child: Text(
                            reportData["conversations"].toString(),
                            style: TextStyle(
                              color: Color(0xFF363636),
                              fontWeight: FontWeight.bold,
                              fontSize: 24
                            )
                          )
                        )
                      )
                    ]
                  )
                )
              )
            ]
          ), 
          Row(
            children: [
              StressMeterWidget(reportData: reportData),
              Expanded(
                child: Column(
                  children: [
                    Container(
                      margin: EdgeInsets.only(bottom: 8, top: 8, left: 4, right: 8),
                      padding: EdgeInsets.all(8),
                      height: MediaQuery.of(context).size.height * 0.15,
                      decoration: BoxDecoration(
                        color: Color(0xFFFFAA8A),
                        borderRadius: BorderRadius.circular(10)
                      ),
                      child: Column(
                        children: [
                          Align(
                            alignment: Alignment.centerLeft,
                            child: Text(
                              "Time spent (avg.)",
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold
                              )
                            )
                          ),
                          Expanded(
                            child: Align(
                              alignment: Alignment.center,
                              child: Text(
                                reportData["timeSpent"].toString(),
                                style: TextStyle(
                                  color: Color(0xFF363636),
                                  fontWeight: FontWeight.bold,
                                  fontSize: 24
                                )
                              )
                            )
                          )
                        ]
                      )
                    ),
                    Interests(reportData: reportData)
                  ]
                )
              )
            ]
          ),
          ConversationReport(reportData: reportData)
        ]
      )
    )
    );
  }
}